# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-23 03:56
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_title', models.CharField(default='', max_length=32)),
                ('article_sendtime', models.DateTimeField(auto_now_add=True, null=True)),
                ('article_up', models.IntegerField(default=0)),
                ('article_down', models.IntegerField(default=0)),
                ('article_info', models.CharField(default='', max_length=1000)),
                ('article_content', DjangoUeditor.models.UEditorField(default='', verbose_name='content')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(default='', max_length=10)),
                ('user_id', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('reply', models.CharField(default='', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('content', models.CharField(default='', max_length=150)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('label_id', models.AutoField(primary_key=True, serialize=False)),
                ('label_name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_id', models.CharField(default='', max_length=50)),
                ('follow_id', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='', max_length=50)),
                ('user_email', models.CharField(default='', max_length=100)),
                ('user_password', models.CharField(default='', max_length=30)),
                ('user_sex', models.CharField(default='', max_length=4)),
                ('user_phonenum', models.CharField(default='', max_length=30)),
                ('user_birth', models.CharField(default='', max_length=30)),
                ('user_hobby', models.CharField(default='', max_length=30)),
                ('user_img', models.ImageField(default='default.JPG', upload_to='logo', verbose_name='头像')),
                ('user_follow', models.IntegerField(default='0')),
                ('user_fan', models.IntegerField(default='0')),
                ('user_header', models.ImageField(blank=True, null=True, upload_to=main.models.user_directory_path, verbose_name='头像')),
            ],
        ),
        migrations.AddField(
            model_name='label',
            name='d',
            field=models.ManyToManyField(to='main.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='usr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
        migrations.AddField(
            model_name='articletype',
            name='r',
            field=models.ManyToManyField(to='main.User'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Label'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ArticleType'),
        ),
        migrations.AddField(
            model_name='article',
            name='usr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
    ]
