# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-23 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='d',
        ),
        migrations.AddField(
            model_name='label',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.User'),
            preserve_default=False,
        ),
    ]
