# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-23 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_article_article_isdelete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='user_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
