# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-23 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191123_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(default='', max_length=20)),
                ('label_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Label')),
            ],
        ),
    ]
