# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-23 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_articlelabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelabel',
            name='label_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
