# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-24 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191124_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='usr',
        ),
        migrations.AddField(
            model_name='article',
            name='article_user',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(default='', max_length=32),
        ),
    ]
