# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-24 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191124_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_user',
        ),
        migrations.AddField(
            model_name='article',
            name='usr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ArticleType'),
        ),
    ]
