# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-26 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191124_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_label',
        ),
    ]
