# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-26 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_article_article_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='article_id',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='usr_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
