# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-26 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_comment_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='floor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
