# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-26 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_comment_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='floor',
            field=models.IntegerField(default=1),
        ),
    ]
