# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-27 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_user_user_sentence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_img',
        ),
    ]
